### ISSUE TITLE
Broken with recent associated_types changes

### ISSUE THREAD

**Issue by darinmorrison** [darinmorrison/type-nats.rs#4]
There are several problems building with the most recent associated types changes. I tried changing things around a bit but haven't had any luck getting it back into a working state. Need to investigate further and maybe open an issue with a minimal example.

@jroesch any thoughts on this?

**Comment by darinmorrison** [comment]
Build is working again with 307c785. Closing unless I run into more issues…

**Comment by jroesch** [comment]
sorry I missed this Rust creates too many GH notifications and things get lost :(

**Comment by darinmorrison** [comment]
Ah, no worries :) I managed to refactor most of it anyway IIRC.
